### ISSUE TITLE
Invitación para integración de Dataset a nivel latinoamérica

### ISSUE THREAD

**Issue by pablodz** [martingra/COVID19Argentina#1]
Hola, junto con una organización sin fines de lucro se está tratando de centralizar la información de contagiados/muertos/recuperados covid-19 y estamos buscando un encargado por país. En tu caso Argentina.

El formato del csv se está manejando acorde al formato global https://github.com/CSSEGISandData/COVID-19 para luego poder juntar la data.
Esto comprende las siguientes columnas:
![image](https://user-images.githubusercontent.com/28235457/77368025-6394bc00-6d29-11ea-9e53-da90978a510e.png)

Para tu país serían las siguientes filas, una actualización diaria:
![image](https://user-images.githubusercontent.com/28235457/77368077-7dce9a00-6d29-11ea-9ceb-8471d5a6d843.png)

Podrías comentarme si estás interesado en aportar porfavor.
El dataset centralizado se propone en este repositorio: https://github.com/DataScienceResearchPeru/covid-19_latinoamerica
Se te puede dar acceso nivel `Maintainer` al repositorio mencionado, ya hay encargados de varios países.

**Comment by martingra** [comment]
Hola! muchas gracias por el contacto! Me encantaría poder participar y sumar a este proyecto.

Tengo los datos actualizados y lo voy haciendo en base a informes diarios del ministerio de salud argentino y los periódicos, ya que los informes suelen no ser del todo completos. 

Mi único problema es que no hay un seguimiento muy estricto de recuperados, lo que puede complicar un poco las cosas. Lo que es infectados y fallecidos si lo tengo actualizado.

Comentame cómo quieres que sigamos.

Saludos

**Comment by pablodz** [comment]
Hola, sí, genial.

Respecto a la data de los recuperados un aproximado es suficiente, ya a largo plazo podríamos arreglar eso ya que es igual en todos los países de Latinoamérica.

Te doy acceso al repositorio entonces. Confirmame el acceso. Directamente edita los archivos correspondientes.
